<?php

namespace humhub\modules\questionanswer\models;

use humhub\components\ActiveRecord;
use humhub\modules\content\interfaces\ContentTitlePreview;
use humhub\modules\search\interfaces\Searchable;
use Yii;
use yii\helpers\Url;

/**
 * This is the model class for table "question".
 *
 * The followings are the available columns in table 'question':
 * @property integer $id
 * @property integer $question_id
 * @property string $post_title
 * @property string $post_text
 * @property string $post_type
 * @property string $created_at
 * @property integer $created_by
 * @property string $updated_at
 * @property integer $updated_by
 */
//class Answer extends HActiveRecord implements ISearchable
class Answer extends ActiveRecord implements Searchable, ContentTitlePreview
{

	public $wallEntryClass = 'humhub\modules\questionanswer\widgets\WallEntry';

    /**
	 * @return string the associated database table name
	 */
	public static function tableName()
	{
		return 'question';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array(['post_text', 'post_type'], 'required'),
			array(['question_id', 'created_by', 'updated_by'], 'integer'),
			array('post_title', 'string', 'max'=>255),
			array('post_type', 'string', 'max'=>8),
			array(['created_at', 'updated_at'], 'safe'),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, question_id, post_title, post_text, post_type, created_at, created_by, updated_at, updated_by', 'safe', 'on'=>'search'),
		);
	}

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels()
    {
        return array(
            'id' => 'ID',
            'question_id' => 'Question',
            'post_title' => 'Post Title',
            'post_text' => 'Post Text',
            'post_type' => 'Post Type',
            'created_at' => 'Created At',
            'created_by' => 'Created By',
            'updated_at' => 'Updated At',
            'updated_by' => 'Updated By',
        );
    }

	public function afterSave($insert, $changedAttributes)
	{
		$activity = new \humhub\modules\questionanswer\activities\Answer();
		$activity->source = $this;
		$activity->originator = Yii::$app->user->getIdentity();
		$activity->container = Yii::$app->user->getIdentity();
		$activity->create();

		parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
	}

	public function getContentName()
	{
		return Yii::t('CommentModule.models_comment', 'Answer');
	}

	public function getContentDescription()
	{
		return $this->post_text;
	}

    /**
	 * @return array relational rules.
	 */
	public function relations()
	{
        return array(
            'user' => array(static::BELONGS_TO, 'User', 'created_by'),
            'comments' => array(static::HAS_MANY, 'QAComment', 'parent_id'),
        );
	}

	public function getComments()
	{
		return $this->hasMany(QAComment::className(), ['parent_id' => 'id']);
	}

    /**
     * Returns the Wall Output
     */
    public function getWallOut()
    {
//        return "Hello World";
         return Yii::app()->getController()->widget('application.modules.questionanswer.widgets.AnswerWallEntryWidget', array('answer' => $this), true);
    }

    /**
     * Returns an array of informations used by search subsystem.
     * Function is defined in interface ISearchable
     *
     * @return Array
     */
    public function getSearchAttributes()
    {
        $attributes = [];

        return $attributes;
    }

    /**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('question_id',$this->question_id);
		$criteria->compare('post_title',$this->post_title,true);
		$criteria->compare('post_text',$this->post_text,true);
		$criteria->compare('post_type',$this->post_type,true);
		$criteria->compare('created_at',$this->created_at,true);
		$criteria->compare('created_by',$this->created_by);
		$criteria->compare('updated_at',$this->updated_at,true);
		$criteria->compare('updated_by',$this->updated_by);

		$criteria->compare('post_type', 'answer');

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}


	/** 
	 * Add scopes to Answer model
	 */
    public function scopes()
    {
        return array(
            'answers'=>array(
                'condition'=>"post_type='answer'",
            )
        );
    }

	/** 
	 * Filters results by the question_id
	 * @param $question_id
	 */
	public function question($question_id)
	{
	    $this->getDbCriteria()->mergeWith(array(
	        'condition'=>"question_id=:question_id", 
	        'params' => array(':question_id' => $question_id)
	    ));

	    return $this;
	}

	/** 
	 * Returns a list of questions with stats
	 */
	public static function overview($question_id) 
	{

		$sql = "SELECT q.id, q.question_id, q.post_title, q.post_text, q.post_type, q.created_by, q.created_at, (COUNT(DISTINCT up.id)) as score, (COUNT(DISTINCT up.id)) as vote_count, COUNT(DISTINCT up.id) as up_votes, COUNT(DISTINCT down.id) as down_votes, best.vote_type as answer_status
				FROM question q
				LEFT JOIN question_votes up ON (q.id = up.post_id AND up.vote_on = 'answer' AND up.vote_type = 'up')
				LEFT JOIN question_votes down ON (q.id = down.post_id AND down.vote_on = 'answer' AND down.vote_type = 'down')
				LEFT JOIN question_votes best ON (q.id = best.post_id AND best.vote_on = 'answer' AND best.vote_type = 'accepted_answer') 
                WHERE q.post_type = 'answer'
				AND q.question_id = :parent_id
				GROUP BY q.id
				ORDER BY score DESC, vote_count DESC";

		return \Yii::$app->db->createCommand($sql)->bindValue('parent_id', $question_id)->queryAll();

	}


    /**
     * Returns URL to the Question
     *
     * @param array $parameters
     * @return string
     */
    public function getUrl($parameters = array())
    {
    	return  Url::toRoute('//questionanswer/question/view', $parameters);
    }

    /**
     * Returns the Search Result Output
     */
    public function getSearchResult()
    {
        return Yii::$app->getController()->widget('application.modules.questionanswer.widgets.AnswerSearchResultWidget', array('question' => Question::findOne($this->question_id), 'answer' => $this), true);
    }
}
